### ISSUE TITLE
File uploading: consider not to download entire file in memory - send inputStream instead

### ISSUE THREAD

**Issue by MaximTkachenko** [justeat/ZendeskApiClient#143]
I mean this one
```
using (var stream = new MemoryStream())
{
    inputStream.CopyTo(stream);
    using (var content = new ByteArrayContent(stream.ToArray()))
    {
        content.Headers.ContentType = new MediaTypeHeaderValue("application/binary");

        return await client.PostAsync(requestUri, content).ConfigureAwait(false);
    }
}
```

**Comment by jonathanstowell** [comment]
Hi @MaximTkachenko I'm not entirely sure what you mean. This method is used when Uploading Attachments to Zendesk and not Downloading. The consumer can provide a Stream containing the file contents however we need to read this in full to POST as part of the HTTP request to Zendesk.

**Comment by MaximTkachenko** [comment]
Why do you need to pull entire file in memory? Can you just send stream directly using StreamContent?

**Comment by jonathanstowell** [comment]
I think I looked into this a while ago and the Zendesk API only accepts application/binary for the upload endpoint: https://developer.zendesk.com/rest_api/docs/support/attachments#using-curl

In order to stream it needs to accept the application/octet-stream header. I guess this is why its loading the whole file into memory.

Are we happy to close this?

**Comment by MaximTkachenko** [comment]
I don't use your library actually. I just want to say that I use Zendesk API directly and sending StreamContent works OK. Please close if you want.

**Comment by jonathanstowell** [comment]
I've created a task for someone to have a look when they get time. https://github.com/justeat/ZendeskApiClient/projects/1#card-24166847
