### ISSUE TITLE
Can't set email identity as verified

### ISSUE THREAD

**Issue by omar** [justeat/ZendeskApiClient#19]
Given a user with an unverified email identity, the Zendesk API docs state to send a `PUT` with the `verified` field set to `true` (see https://developer.zendesk.com/rest_api/docs/core/user_identities#update-a-given-user-identity). However, when calling the code below, an error is thrown because the ZendeskClient sends a `POST` with an existing User Identity at which point the API returns an error (see https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Client/Resources/UserIdentityResource.cs#L31-L33).

```
var zendeskClient = GetYourZendeskClient();
var user = GetYourZendeskUser()
var userIdentities = zendeskClient.UserIdentities.GetAll(user.Id.Value);
var emailIdentity = userIdentities.Results.FirstOrDefault(ui => ui.Type == "email");
emailIdentity.Verified = true;

zendeskClient.UserIdentities.Put(new UserIdentityRequest()
{
    Item = emailIdentity
});
```

The client should just send a `PUT` to the API with the specified parameters.

**Comment by kate-r** [comment]
This was because of https://developer.zendesk.com/rest_api/docs/core/user_identities#allowed-for

Through the zendesk api, you're unable to do things like modify the user's email address. It requires they are deleted and readded. Doing this in the Put request is a bad idea though because this it's not explicit that that's what's happening. It also means you can't verify a user, as you say above.

Thanks for the PR. I've merged it in and gone up a major version number as this is a breaking change if people are using the put method to update things like email addresses but verifying users through the zendesk portal.

https://www.nuget.org/packages/ZendeskApi.Client/1.0.65
