### ISSUE TITLE
Unable to set custom fields on new ticket

### ISSUE THREAD

**Issue by bmnielsen** [justeat/ZendeskApiClient#33]
The Ticket.CustomFields property is private set, so it isn't possible to set custom fields on a new ticket, as the property defaults to null.

I can work around this by setting the property via reflection, but obviously this isn't a desirable solution.

Any reason why the field shouldn't just be public?

**Comment by kate-r** [comment]
Hi,

I made the custom fields list private because the list is set at account level, with the values of items in the list being set at ticket level. 

I can see the use-case for being able to set items in the list and I can see I have a PR to do that update so if this is something people need, then I will merge the PR.

Thanks,

Kate

**Comment by kate-r** [comment]
I've merged the PR for this and published the updated client.
