### ISSUE TITLE
Ticket custom fields should be longs, not ints

### ISSUE THREAD

**Issue by mbishopim3** [justeat/ZendeskApiClient#47]
According to the ZenDesk documentation, custom field IDs are `long`, not `int`.

**Comment by hjaltethor** [comment]
Hi! Thanks for commenting on the client. 

I just checked the Zendesk documentation and you are correct. We should have used `long` instead of `int` for the IDs. For anyone interested, the relevant part is here: https://developer.zendesk.com/rest_api/docs/core/introduction#id-integers.

If you're up for doing a pull request containing this change, I'd be very happy to accept it.

**Comment by hjaltethor** [comment]
This is now in the latest version of the client on nuget.

**Comment by mbishopim3** [comment]
Works, thanks for the speed!
