### ISSUE TITLE
Updating domain_names for an Organization ?!?

### ISSUE THREAD

**Issue by nirwana101** [justeat/ZendeskApiClient#51]
Hello,

I have used this Zendesk API-client for creating Organizations and End-Users. 
Also retrieving Tickets and TicketComments worked like a charm. Thank you for making this possible.

Now I trying the next step: updating an Organization with one or morre domain_names.
Using the Zendesk-ID for this Organization I am trying to send an update.

IResponse<Organization> response = client.Organizations.Put(new OrganizationRequest { Item = org });

A list of domainnames for each customer I placed in a textfield in our CRM-system, seperated by a comma. In the Organization-object I added a C# string-array with domain_names, like this:

string[] domainNames = value.Trim().Split(' ');
org.domain_names = domainNames;

When I send the update the domain name is not added to the organization.
I also do not see an exception, so I assume everything goes fine.
But when I update a normal string-field (like the organization's name) I see this change in Zendesk. So it looks like normal updates are working fine, but arrays aren't supported (yet).

I also tried GETting an organization.
When I do so the array-fields (like domain_names, tags) also stay empty (= null).
The other fields are filled.

Am I doing something wrong here ? 
Or is this not yet supported by this C# Zendesk API Client ?

Any help is appreciated.
Thanks in advance !

**Comment by hjaltethor** [comment]
Hello!

When we initially created the C# Zendesk client, we only added the fields needed to represent an restaurant as an organization.

Since then we've open sourced the project and added lots more fields to the models, but we still have unused fields.

I'll see about creating an update to the client early next week with some changes we've already tested internally to add tags and, as you've requested, domain names to the Organizations.

If you want to give it a try yourself, have a look at https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Contracts/Models/Organization.cs. You'll need to change the type for domain_names from object to list<string> (similar to tags) and move them to the un-ignored section (adding the apprioriate tags).

Here's an example (unrelated) PR that does the same:
https://github.com/justeat/ZendeskApiClient/pull/38/files

Let me know if you have any other questions, and thank you for commenting on our project.

Thanks,
Hjalte

**Comment by nirwana101** [comment]
Hjalte,

Thank you for your comment.

I have just implemented your fix and it seems to be working fine. I have updated some organizations in Zendesk and these now have domain-names listed. Thank you again for your directions, because these pointed me into the right direction.

I have attached the changed file (I have not used Github to update files before):

[Organization.zip](https://github.com/justeat/ZendeskApiClient/files/402742/Organization.zip)

I hope that you can update this file in your nice project. It was very helpful.

-- 
Martijn
